// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type RevokedToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	RevokedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        sql.NullString
	Phone        sql.NullString
	PasswordHash string
	DisplayName  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
