version: '3'
services:
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: jamhub
    ports:
      - "5432:5432"
  jamhub_app:
    container_name: jamhub_app
    image: bkohler93/jamhub_app:1.0.0
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: "postgres://root:password@db:5432/jamhub"
      SUPER_SECRET: "sadieboosecret"
